import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import Module, {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import ts from 'typescript';
import RealStripe from 'stripe';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),require=createRequire(import.meta.url);
const originalResolve=Module._resolveFilename, originalLoad=Module._load;
const cookieJar=new Map();
const session={id:'11111111-1111-4111-8111-111111111111',access_token:'22222222-2222-4222-8222-222222222222',checkout_mode:'test',payment_status:'pending',raw_answers:{email:'synthetic@example.com',favoriteMemory:'These exact  words stay private'}};
let orders=[],checkouts=new Map(),createCalls=[],generationCalls=0,generationClaimed=false;
class FixtureStripe extends RealStripe {constructor(...args){super(...args);this.checkout={sessions:{create:async(body,options)=>{createCalls.push({body,options});let existing=[...checkouts.values()].find(c=>c.key===options.idempotencyKey);if(existing)return existing;const c={id:'cs_test_'+createCalls.length,key:options.idempotencyKey,status:'open',payment_status:'unpaid',livemode:false,mode:'payment',url:'https://checkout.stripe.com/c/pay/synthetic',metadata:body.metadata,client_reference_id:body.client_reference_id,amount_total:2900,currency:'usd',payment_intent:'pi_test_fixture'};checkouts.set(c.id,c);return c;},retrieve:async(id)=>{assert.ok(checkouts.has(id));return structuredClone(checkouts.get(id));}}};}}
Module._resolveFilename=function(id,...rest){return originalResolve.call(this,id.startsWith('@/')?path.join(root,'src',id.slice(2)):id,...rest)};
Module._load=function(id,...rest){if(id==='server-only')return {};if(id==='stripe')return FixtureStripe;if(id==='next/headers')return {cookies:async()=>({get:k=>cookieJar.has(k)?{value:cookieJar.get(k)}:undefined,set:(k,v)=>cookieJar.set(k,v)})};return originalLoad.call(this,id,...rest)};
Module._extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,f);
const repo={
 requireSession:async(id,key)=>{if(id!==session.id||key!==session.access_token)throw new Error('invalid_session');return structuredClone(session)},
 sessionFor:async(id,key)=>id===session.id&&key===session.access_token?structuredClone(session):null,
 db:()=>({rpc:async(name,p)=>{if(name==='reserve_song_checkout'){let o=orders.find(o=>o.session_id===p.p_session_id);if(!o){o={id:'33333333-3333-4333-8333-333333333333',session_id:session.id,mode:'test',amount:2900,currency:'usd',origin:p.p_origin,stripe_checkout_id:null,status:'pending',checkout_attempt:1};orders.push(o)}return {data:structuredClone(o),error:null}}
 if(name==='mark_song_checkout_paid'){const o=orders.find(o=>o.id===p.p_order_id);assert.equal(o.stripe_checkout_id,p.p_checkout_id);assert.equal(p.p_amount,2900);o.status='paid';session.payment_status='paid';return {data:structuredClone(session),error:null}}throw new Error(name)},from:()=>{let filters=[],values;const q={select(){return this},eq(k,v){filters.push(o=>o[k]===v);return this},is(k,v){filters.push(o=>o[k]===v);return this},update(v){values=v;return this},maybeSingle(){return this},then(resolve){const rows=orders.filter(o=>filters.every(f=>f(o)));if(values)rows.forEach(o=>Object.assign(o,values));return Promise.resolve({data:values?structuredClone(rows):structuredClone(rows[0]??null),error:null}).then(resolve)}};return q}}),
};
for(const [filename,exports] of [['beta-repository.ts',repo],['beta-generation.ts',{reserveAndStart:async(s)=>{assert.equal(s.payment_status,'paid');if(!generationClaimed){generationClaimed=true;generationCalls++}}}]]){const p=require.resolve('../src/lib/'+filename);require.cache[p]={id:p,filename:p,loaded:true,exports}}
process.env.CHECKOUT_MODE='free';process.env.STRIPE_TEST_SECRET_KEY='sk_test_synthetic_only';process.env.STRIPE_TEST_WEBHOOK_SECRET='whsec_fixture_only';delete process.env.STRIPE_SECRET_KEY;delete process.env.STRIPE_WEBHOOK_SECRET;
const payments=require('../src/lib/payments.ts'),checkoutRoute=require('../src/app/api/checkout/route.ts'),webhook=require('../src/app/api/webhooks/stripe/[mode]/route.ts'),returnRoute=require('../src/app/checkout/return/route.ts');
const checks=[];function pass(s){checks.push(s);console.log('PASS',s)}
assert.equal(payments.publicCheckoutMode(),'free');assert.equal(payments.stripeReady('test'),true);assert.equal(payments.stripeReady('live'),false);process.env.STRIPE_TEST_SECRET_KEY='sk_live_wrong_mode';assert.equal(payments.stripeReady('test'),false);process.env.STRIPE_TEST_SECRET_KEY='sk_test_synthetic_only';pass('Public path remains no-paywall; sandbox/live credentials cannot cross modes');
const headers={'content-type':'application/json',origin:'https://www.yourgiftsmith.com',host:'www.yourgiftsmith.com'};
let r=await checkoutRoute.POST(new Request('https://www.yourgiftsmith.com/api/checkout',{method:'POST',headers,body:JSON.stringify({songId:session.id,accessToken:session.access_token,amount:1})}));assert.equal(r.status,200);assert.equal((await r.json()).url,'https://checkout.stripe.com/c/pay/synthetic');assert.equal(generationCalls,0);assert.equal(cookieJar.get(payments.checkoutCookieName(session.id)),session.access_token);
await Promise.all([payments.createSongCheckout(session),payments.createSongCheckout(session)]);assert.equal(createCalls.length,1);assert.equal(orders.length,1);pass('Hosted checkout reuses the saved order, ignores client price and starts no unpaid music');
const payload=createCalls[0].body;assert.equal(payload.line_items[0].price_data.unit_amount,2900);assert.equal(payload.line_items[0].price_data.currency,'usd');assert.deepEqual(payload.allowed_payment_method_types,['card']);assert.ok(payload.line_items[0].price_data.product_data.description.includes('3 revisions'));assert.ok(!JSON.stringify(payload).includes(session.access_token));assert.ok(!JSON.stringify(payload).includes(session.raw_answers.favoriteMemory));pass('Server fixes $29 USD offer; Stripe receives no private song key or story details');
const c=checkouts.get(orders[0].stripe_checkout_id);
assert.equal(await payments.fulfillCheckout(c.id,'test'),null);assert.equal(generationCalls,0);
const signer=new RealStripe('sk_test_fixture_only');function eventRequest(event,bad=false,mode='test'){const body=JSON.stringify(event);return new Request('https://www.yourgiftsmith.com/api/webhooks/stripe/'+mode,{method:'POST',headers:{'stripe-signature':bad?'invalid':signer.webhooks.generateTestHeaderString({payload:body,secret:process.env.STRIPE_TEST_WEBHOOK_SECRET})},body})}
let event={id:'evt_fixture',type:'checkout.session.completed',livemode:false,data:{object:c}};
r=await webhook.POST(eventRequest(event,true),{params:Promise.resolve({mode:'test'})});assert.equal(r.status,400);assert.equal(generationCalls,0);
r=await webhook.POST(eventRequest(event),{params:Promise.resolve({mode:'test'})});assert.equal(r.status,200);assert.equal(generationCalls,0);pass('Actual Stripe SDK rejects forged signatures; unpaid events never grant access');
c.status='complete';c.payment_status='paid';event={...event,data:{object:c}};
for(const altered of [{amount_total:1},{currency:'eur'},{livemode:true},{metadata:{...c.metadata,song_id:'other-song'}},{client_reference_id:'other-order'}])assert.throws(()=>payments.validatePaidCheckout({...c,...altered},orders[0]));assert.equal(generationCalls,0);pass('Payment validation rejects wrong amount, currency, mode, song and order');
r=await webhook.POST(eventRequest(event),{params:Promise.resolve({mode:'test'})});assert.equal(r.status,200);
await Promise.all([payments.fulfillCheckout(c.id,'test',session.id),webhook.POST(eventRequest(event),{params:Promise.resolve({mode:'test'})})]);assert.equal(session.payment_status,'paid');assert.equal(generationCalls,1);assert.equal(await payments.createSongCheckout(session),null);pass('Signed paid event saves payment and duplicate confirmation invokes one generation claim');
r=await returnRoute.GET(new Request('https://www.yourgiftsmith.com/checkout/return?order='+orders[0].id));assert.equal(r.status,303);assert.ok(r.headers.get('location').includes(session.access_token));assert.ok(r.headers.get('location').includes('payment=confirmed'));cookieJar.clear();r=await returnRoute.GET(new Request('https://www.yourgiftsmith.com/checkout/return?order='+orders[0].id));assert.equal(r.status,401);pass('Return reconciles paid checkout; missing owner cookie cannot reveal a private song link');
orders[0].status='pending';session.payment_status='pending';c.status='expired';c.payment_status='unpaid';await payments.createSongCheckout(session);assert.equal(orders[0].checkout_attempt,2);assert.equal(createCalls.length,2);assert.ok(createCalls[1].options.idempotencyKey.endsWith('-2'));pass('Expired checkout renews safely with a new attempt and idempotency key');
r=await checkoutRoute.POST(new Request('https://www.yourgiftsmith.com/api/checkout',{method:'POST',headers:{...headers,origin:'https://attacker.example'},body:JSON.stringify({songId:session.id,accessToken:session.access_token})}));assert.equal(r.status,403);pass('Cross-origin checkout creation blocked');
fs.writeFileSync(path.join(root,'docs/qa/stripe-server-checks.json'),JSON.stringify({environment:'Real TypeScript routes and payment modules, real Stripe SDK signature verification, controlled provider transport and database fixture. No real payment or provider charge.',checks},null,2)+'\n');
